### ISSUE TITLE
Canvas Size

### ISSUE THREAD

**Issue by Audiobrad** [insidegui/KeyframesPlayer#1]
I noticed if I preview with a canvas size with an aspect ratio other than 1:1 the image is distorted

**Comment by insidegui** [comment]
Can you provide me the file you had opened when this occurred? :)

Thanks!

**Comment by Audiobrad** [comment]
[Plane-Flight-Test.kf.json.zip](https://github.com/insidegui/KeyframesPlayer/files/652635/Plane-Flight-Test.kf.json.zip)

**Comment by insidegui** [comment]
Thanks to @LazyChild, this is now fixed :)

![screen shot 2017-02-24 at 20 56 56](https://cloud.githubusercontent.com/assets/67184/23325413/d0bf47f8-fad3-11e6-88c9-00811a89116b.png)
