### ISSUE TITLE
Integrate with new Keyframes Previewer?

### ISSUE THREAD

**Issue by subtleGradient** [insidegui/KeyframesPlayer#2]
Check out a preview of the new Previewer: https://github.com/facebookincubator/Keyframes/releases/tag/previewer-v1
It fixes a bunch of little bugs and has better error handling. It also includes a Previewer for Android.

It would be awesome if we could integrate your macOS Previewer to the one-click Export+Preview also. It should be pretty easy.

**Comment by subtleGradient** [comment]
Boom!

[KeyframesExporter-macOS-2017-01-11.zip](https://github.com/insidegui/KeyframesPlayer/files/699979/KeyframesExporter-macOS-2017-01-11.zip)

**Comment by subtleGradient** [comment]
I'll land the change to Keyframes After Effects code soon.
```js
  if (macOS.isTheCurrentOS) {
    var macOSPlayerApp = File(__dirname + '/bin-android/Keyframes Player.app');
    if (!macOSPlayerApp.exists) macOSPlayerApp = File('/Applications/Keyframes Player.app');
    if (!macOSPlayerApp.exists) macOSPlayerApp = File('~/Downdloads/Keyframes Player.app');
    if (!macOSPlayerApp.exists) {
      console.warn('"Keyframes Player.app" not found. Install it in /Applications');
    } else {
      // Remove this once Keyframes Player reloads modified animations properly
      macOS.doAppleScript('tell the application "Keyframes Player" to quit');
      macOS.openFileWithApp(path, macOSPlayerApp);
    }
  }
```

**Comment by insidegui** [comment]
Cool! :D
