### ISSUE TITLE
Opening the same JSON file that is already open should trigger reload

### ISSUE THREAD

**Issue by subtleGradient** [insidegui/KeyframesPlayer#3]
`open -a /Applications/Keyframes\ Player.app Keyframes/src/scripts/sample/KeyframesLogo.aep.comp-420-Keyframes\ Logo.kf.json`

1. Open a kf.json file
2. Change that file
3. Open that file again (without closing it first)
4. Should see the latest changes to that JSON

**Comment by insidegui** [comment]
Now the app will automatically reload the file when it is changed externally.
